cargo-features = ["trim-paths"]

[package]
name = "tsees"
version = "1.0.0"
edition = "2021"

[dependencies]
libloading = "0.9.0"
libc = "0.2.180"

[profile.release]
lto = true
strip = true
debug = false
panic = "abort"
opt-level = "z"
trim-paths = "all"
incremental = false
codegen-units = 1